#--------------------------------------------------------#
#      ___     _                  __       _     _
#     /   \___| |_   ___  _____  / /  ___ | |__ | |__  _   _
#    / /\ / _ \ | | | \ \/ / _ \/ /  / _ \| '_ \| '_ \| | | |
#   / /_//  __/ | |_| |>  <  __/ /__| (_) | |_) | |_) | |_| |
#  /___,' \___|_|\__,_/_/\_\___\____/\___/|_.__/|_.__/ \__, |
#                                                      |___/
#--------------------------------------------------------#

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | GENERAL SETTINGS                         |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Check for latest SpigotMC updates (recommended).
check-updates: true

# Double jump true/false.
double-jump: true

# Particle Menu.
particle-menu:
  enabled: true
  slot: 0

# Server Selector Menu.
selector-item:
  enabled: true
  slot: 4

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | WORLD EVENT SETTINGS                     |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Players cant break blocks.
block-break: false
block-place: false
interact: false
fall-damage: false
void-teleport: false
item-pickup: false

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | SCOREBOARD                               |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

scoreboard-visible:
  # Should the scoreboard feature be enabled?
  enabled: true

scoreboard:
  title: '&#1dfb83&lM&#24fb8e&lA&#2bfc99&lZ&#32fca3&lE&#39fdae&lM&#40fdb9&lC'
  lines:
    - '     &7%server_time_d MMMMM yyyy%'
    - ' &r'
    - ' &fRank: &cEigenaar'
    - '  &r'
    - ' &7&oGebruik de server'
    - ' &7&oselector om naar'
    - ' &7&oeen server te gaan.'
    - '   &r'
    - ' &fLobby: &a%bungee_lobby%'
    - ' &fSurvival: &a%bungee_season3%'
    - '&r'
    - '&7play.trophicmc.nl'

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# |TABLIST                                   |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

tab-visible: false

tab:
  header:
  - ""
  - "&8&L-------------"
  - ""
  footer:
  - ""
  - "&8&L-------------"
  - ""