# LobbyPlugin made by 7Bence

# Join item

particle-menu: true
particle-menu-title: "&aParticle Menu"


particle-chest:
  name: "&aCosmetics Menu"
  lore:
    - "&7Rechter-klik om het menu te openen! "

# Double jump true/false

double-jump: true

# Scoreboard

scoreboard:
  title: '&#1dfb83&lM&#24fb8e&lA&#2bfc99&lZ&#32fca3&lE&#39fdae&lM&#40fdb9&lC'
  lines:
    - '     &7%server_time_d MMMMM yyyy%'
    - ' &r'
    - ' &fRank: &cEigenaar'
    - '  &r'
    - ' &7&oGebruik de server'
    - ' &7&oselector om naar'
    - ' &7&oeen server te gaan.'
    - '   &r'
    - ' &fLobby: &a%bungee_lobby%'
    - ' &fSurvival: &a%bungee_season3%'
    - '&r'
    - '&7play.trophicmc.nl'

tab-visible: false
tab:
  header:
  - ""
  - "&8&L-------------"
  - ""
  footer:
  - ""
  - "&8&L-------------"
  - ""