# LobbyPlugin made by 7Bence

# Join item

particle-menu: true
particle-menu-title: "&aParticle Menu"


particle-chest:
  name: "&aCosmetics Menu"
  lore:
    - "&7Rechter-klik om het menu te openen! "

# GUI Menu server selector

server-selector-title: "          &a&lServer Selector"

server-selector:
  1:
    name: "&#1dfb83&lSurvival"
    item: 'GRASS_BLOCK'
    glow: true
    slot: 10
    lore:
      - ''
      - '&f- &7Gegarandeerd geen lagg'
      - '&f- &7Volledig 1.18.x'
      - '&f- &7Vriendelijke spelers!'
      - '&f- &7Elke week meerdere events!'
      - ''
      - '&f- &7Spelers: &a%bungee_survival%'
      - ''
      - '&a&l➜ &aKlik om te verbinden!'
    action: "server_survival"


# Double jump true/false

double-jump: true

# Scoreboard

scoreboard:
  title: '&#1dfb83&lM&#24fb8e&lA&#2bfc99&lZ&#32fca3&lE&#39fdae&lM&#40fdb9&lC'
  lines:
    - '     &7%server_time_d MMMMM yyyy%'
    - ' &r'
    - ' &fRank: &cEigenaar'
    - '  &r'
    - ' &7&oGebruik de server'
    - ' &7&oselector om naar'
    - ' &7&oeen server te gaan.'
    - '   &r'
    - ' &fLobby: &a%bungee_lobby%'
    - ' &fSurvival: &a%bungee_season3%'
    - '&r'
    - '&7play.trophicmc.nl'
