name: LobbyPlugin
version: '${project.version}'
main: dev.bence.lobbyplugin.LobbyPlugin
api-version: 1.19

depend: [PlaceholderAPI]

commands:
  reload:
    description: Reloads the config
  cosmetic:
    description: opensmenu
